//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineBuilder.Samples.EventsHostAdapers {
    
    
    public class DocumentOpenedEventArgsViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedEventArgsContract {
        
        private PipelineBuilder.Samples.Events.DocumentOpenedEventArgs _view;
        
        public DocumentOpenedEventArgsViewToContractHostAdapter(PipelineBuilder.Samples.Events.DocumentOpenedEventArgs view) {
            _view = view;
        }
        
        internal PipelineBuilder.Samples.Events.DocumentOpenedEventArgs GetSourceView() {
            return _view;
        }
    }
}

