//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineBuilder.Samples.EventsHostAdapers {
    
    
    public class DocumentOpenedEventArgsContractToViewHostAdapter : PipelineBuilder.Samples.Events.DocumentOpenedEventArgs {
        
        private PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedEventArgsContract _contract;
        
        private System.AddIn.Pipeline.ContractHandle _handle;
        
        static DocumentOpenedEventArgsContractToViewHostAdapter() {
        }
        
        public DocumentOpenedEventArgsContractToViewHostAdapter(PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedEventArgsContract contract) {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        
        internal PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedEventArgsContract GetSourceContract() {
            return _contract;
        }
    }
}

