//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineBuilder.Samples.EventsHostAdapers {
    
    
    public class DocumentOpenedEventArgsHostAdapter {
        
        internal static PipelineBuilder.Samples.Events.DocumentOpenedEventArgs ContractToViewAdapter(PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedEventArgsContract contract) {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(DocumentOpenedEventArgsViewToContractHostAdapter)))) {
                return ((DocumentOpenedEventArgsViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else {
                return new DocumentOpenedEventArgsContractToViewHostAdapter(contract);
            }
        }
        
        internal static PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedEventArgsContract ViewToContractAdapter(PipelineBuilder.Samples.Events.DocumentOpenedEventArgs view) {
            if (view.GetType().Equals(typeof(DocumentOpenedEventArgsContractToViewHostAdapter))) {
                return ((DocumentOpenedEventArgsContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else {
                return new DocumentOpenedEventArgsViewToContractHostAdapter(view);
            }
        }
    }
}

