//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineBuilder.Samples.EventsHostAdapers {
    
    
    public class IAppObjectContractToViewHostAdapter : PipelineBuilder.Samples.Events.IAppObject {
        
        private PipelineBuilder.Samples.Events.Contracts.IAppObjectContract _contract;
        
        private System.AddIn.Pipeline.ContractHandle _handle;
        
        private IDocumentOpenedHandlerViewToContractHostAdapter DocumentOpened_Handler;
        
        private static System.Reflection.MethodInfo s_DocumentOpenedAddFire;
        
		public event System.EventHandler<PipelineBuilder.Samples.Events.DocumentOpenedEventArgs>DocumentOpened{
			add{
				if (_DocumentOpened == null)
			{
				_contract.DocumentOpenedAdd(DocumentOpened_Handler);
			}
			_DocumentOpened += value;
			}
			remove{
				_DocumentOpened -= value;
			if (_DocumentOpened == null)
			{
				_contract.DocumentOpenedRemove(DocumentOpened_Handler);
			}
			}
		}
        
        static IAppObjectContractToViewHostAdapter() {
            s_DocumentOpenedAddFire = typeof(IAppObjectContractToViewHostAdapter).GetMethod("Fire_DocumentOpened", ((System.Reflection.BindingFlags)(36)));
        }
        
        public IAppObjectContractToViewHostAdapter(PipelineBuilder.Samples.Events.Contracts.IAppObjectContract contract) {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
            DocumentOpened_Handler = new IDocumentOpenedHandlerViewToContractHostAdapter(this, s_DocumentOpenedAddFire);
        }
        
        private event System.EventHandler<PipelineBuilder.Samples.Events.DocumentOpenedEventArgs> _DocumentOpened;
        
        internal virtual void Fire_DocumentOpened(PipelineBuilder.Samples.Events.DocumentOpenedEventArgs args) {
            if ((_DocumentOpened == null)) {
            }
            else {
                _DocumentOpened.Invoke(this, args);
            }
        }
        
        internal PipelineBuilder.Samples.Events.Contracts.IAppObjectContract GetSourceContract() {
            return _contract;
        }
    }
}

