//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineBuilder.Samples.EventsHostAdapers {
    
    
    public class IDocumentOpenedHandlerContractToViewHostAdapter {
        
        private PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedHandlerContract _contract;
        
        private System.AddIn.Pipeline.ContractHandle _handle;
        
        public IDocumentOpenedHandlerContractToViewHostAdapter(PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedHandlerContract contract) {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        
        public void Handler(object sender, PipelineBuilder.Samples.Events.DocumentOpenedEventArgs args) {
            _contract.Handle(PipelineBuilder.Samples.EventsHostAdapers.DocumentOpenedEventArgsHostAdapter.ViewToContractAdapter(args));
        }
        
        internal PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedHandlerContract GetSourceContract() {
            return _contract;
        }
    }
}

