//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineBuilder.Samples.EventsAddInAdapters {
    
    
    public class DocumentOpenedEventArgsAddInAdapter {
        
        internal static PipelineBuilder.Samples.Events.DocumentOpenedEventArgs ContractToViewAdapter(PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedEventArgsContract contract) {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(DocumentOpenedEventArgsViewToContractAddInAdapter)))) {
                return ((DocumentOpenedEventArgsViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else {
                return new DocumentOpenedEventArgsContractToViewAddInAdapter(contract);
            }
        }
        
        internal static PipelineBuilder.Samples.Events.Contracts.IDocumentOpenedEventArgsContract ViewToContractAdapter(PipelineBuilder.Samples.Events.DocumentOpenedEventArgs view) {
            if (view.GetType().Equals(typeof(DocumentOpenedEventArgsContractToViewAddInAdapter))) {
                return ((DocumentOpenedEventArgsContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else {
                return new DocumentOpenedEventArgsViewToContractAddInAdapter(view);
            }
        }
    }
}

