//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineBuilder.Samples.EventsAddInAdapters {
    
    
    public class IAppObjectAddInAdapter {
        
        internal static PipelineBuilder.Samples.Events.IAppObject ContractToViewAdapter(PipelineBuilder.Samples.Events.Contracts.IAppObjectContract contract) {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IAppObjectViewToContractAddInAdapter)))) {
                return ((IAppObjectViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else {
                return new IAppObjectContractToViewAddInAdapter(contract);
            }
        }
        
        internal static PipelineBuilder.Samples.Events.Contracts.IAppObjectContract ViewToContractAdapter(PipelineBuilder.Samples.Events.IAppObject view) {
            if (view.GetType().Equals(typeof(IAppObjectContractToViewAddInAdapter))) {
                return ((IAppObjectContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else {
                return new IAppObjectViewToContractAddInAdapter(view);
            }
        }
    }
}

