//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineBuilder.Samples.EventsAddInAdapters {
    
    
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class ISampleAddInViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, PipelineBuilder.Samples.Events.Contracts.ISampleAddInContract {
        
        private PipelineBuilder.Samples.Events.ISampleAddIn _view;
        
        public ISampleAddInViewToContractAddInAdapter(PipelineBuilder.Samples.Events.ISampleAddIn view) {
            _view = view;
        }
        
        public virtual void Initialize(PipelineBuilder.Samples.Events.Contracts.IAppObjectContract appObject) {
            _view.Initialize(PipelineBuilder.Samples.EventsAddInAdapters.IAppObjectAddInAdapter.ContractToViewAdapter(appObject));
        }
        
        public virtual void Shutdown() {
            _view.Shutdown();
        }
        
        internal PipelineBuilder.Samples.Events.ISampleAddIn GetSourceView() {
            return _view;
        }
    }
}

