//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipelineBuilder.Samples.EventsAddInAdapters {
    
    
    public class ISampleAddInContractToViewAddInAdapter : PipelineBuilder.Samples.Events.ISampleAddIn {
        
        private PipelineBuilder.Samples.Events.Contracts.ISampleAddInContract _contract;
        
        private System.AddIn.Pipeline.ContractHandle _handle;
        
        static ISampleAddInContractToViewAddInAdapter() {
        }
        
        public ISampleAddInContractToViewAddInAdapter(PipelineBuilder.Samples.Events.Contracts.ISampleAddInContract contract) {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        
        public void Initialize(PipelineBuilder.Samples.Events.IAppObject appObject) {
            _contract.Initialize(PipelineBuilder.Samples.EventsAddInAdapters.IAppObjectAddInAdapter.ViewToContractAdapter(appObject));
        }
        
        public void Shutdown() {
            _contract.Shutdown();
        }
        
        internal PipelineBuilder.Samples.Events.Contracts.ISampleAddInContract GetSourceContract() {
            return _contract;
        }
    }
}

